# Generated by Django 3.2.20 on 2023-08-17 14:07
# /usr/home/sso/userdb/venv/lib/python3.9/site-packages/uniauth_saml2_idp/migrations/0003_auto_20230817_1407.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniauth_saml2_idp', '0002_auto_20210408_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadatastore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='attribute_mapping',
            field=models.TextField(blank=True, default='{\n    "displayName": "get_full_name",\n    "email": "email",\n    "givenName": "first_name",\n    "sn": "last_name"\n}', help_text='Attribute that would be release to this SP, in JSON format.', null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='attribute_processor',
            field=models.CharField(blank=True, default='uniauth_saml2_idp.processors.base.BaseProcessor', help_text='"package.file.classname", example: "uniauth_saml2_idp.base.processors.BaseProcessor"', max_length=256),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]

