# Generated by Django 3.2.5 on 2021-07-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210727_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ManyToManyField(to='users.Department'),
        ),
    ]
