# Generated by Django 3.0.14 on 2022-04-13 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppPasswords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="App Name"
                    ),
                ),
                (
                    "userid",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="App Username or ID"
                    ),
                ),
                ("password", models.TextField()),
                ("salt", models.TextField()),
                ("key", models.TextField()),
                ("cert", models.TextField()),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "App Passwords",
            },
        ),
    ]
