# Generated by Django 3.0.14 on 2022-04-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_apppasswords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppasswords",
            name="cert",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="apppasswords",
            name="key",
            field=models.TextField(blank=True),
        ),
    ]
