# Generated by Django 3.0.14 on 2022-04-13 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20220413_0734"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apppasswords",
            unique_together={("user", "app")},
        ),
    ]
