# Generated by Django 3.0.14 on 2022-05-03 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_auto_20220421_0949"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="nickname",
        ),
    ]
