# Generated by Django 3.2.15 on 2022-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_auto_20220901_1028"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UnixShells",
        ),
        migrations.AlterField(
            model_name="apppasswords",
            name="app",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Nextcloud", "Nextcloud"),
                    ("Email", "Email"),
                    ("Gitlab", "Gitlab"),
                ],
                max_length=64,
                verbose_name="App Name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="unixname",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Unix Login Name",
            ),
        ),
    ]
