# Generated by Django 3.2.15 on 2022-09-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_auto_20220907_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrolemap",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("USER", "User")], max_length=128
            ),
        ),
        migrations.DeleteModel(
            name="Roles",
        ),
    ]
