# Generated by Django 3.2.15 on 2022-09-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20220908_0636"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppasswords",
            name="app",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEXTCLOUD", "Nextcloud"),
                    ("EMAIL", "Email"),
                    ("GITLAB", "Gitlab"),
                ],
                max_length=64,
                verbose_name="App Name",
            ),
        ),
    ]
