# Generated by Django 3.2.15 on 2022-09-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_auto_20220909_1404"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="alt_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Alternate Email Address",
            ),
        ),
    ]
