# Generated by Django 3.2.15 on 2022-09-09 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_customuser_alt_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppasswords",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apppasswords",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userrolemap",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userrolemap",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
