# Generated by Django 3.2.15 on 2022-11-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_auto_20220909_1646"),
    ]

    operations = [
        migrations.AddField(
            model_name="apppasswords",
            name="name",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Entry Name"
            ),
        ),
        migrations.AlterField(
            model_name="apppasswords",
            name="application",
            field=models.CharField(
                blank=True,
                choices=[("EMAIL", "Email")],
                max_length=64,
                verbose_name="Application",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apppasswords",
            unique_together={("user", "application", "name")},
        ),
    ]
