# Generated by Django 3.2.15 on 2022-11-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_auto_20221121_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apppasswords",
            name="application",
            field=models.CharField(
                choices=[("EMAIL", "Email")], max_length=64, verbose_name="Application"
            ),
        ),
        migrations.AlterField(
            model_name="apppasswords",
            name="username",
            field=models.CharField(max_length=64, verbose_name="Application Username"),
        ),
    ]
