# Generated by Django 3.2.15 on 2022-12-08 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_auto_20221123_1616"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="unixname",
        ),
    ]
