# Generated by Django 3.2.18 on 2023-03-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_auto_20230221_1453"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("USER", "Normal User"),
                    ("HR", "HR User"),
                    ("HOSTING", "Hosting User"),
                    ("RETIRED", "Retired User"),
                ],
                default="USER",
                max_length=16,
                verbose_name="User Type",
            ),
        ),
    ]
