# Generated by Django 3.2.18 on 2023-04-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_update_auto_increment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="original_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Original Email Address",
            ),
        ),
    ]
