# Generated by Django 3.2.20 on 2023-08-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20230421_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('PERSONAL', 'Sabbatical / Other'), ('SICK', 'Sick Leave'), ('PTO', 'Vacation')], max_length=128)),
                ('vacation_message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vacations',
            },
        ),
    ]
