# Generated by Django 3.2.20 on 2023-08-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_uservacations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservacations',
            name='is_active',
        ),
    ]
