# Generated by Django 3.2.20 on 2023-09-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_uservacations_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_ooo',
            field=models.BooleanField(default=False, verbose_name='Out of Office'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ooo_message',
            field=models.TextField(blank=True),
        ),
    ]
