"""
Django settings for sso project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!dji1wG5n9e7hjwp_bkag(q*l3@mm!xlm)tp04-q9a&sm+w)ym"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["127.0.0.1", "sso.emaildomain.com"]

# silence this warning, for django user sessions
SILENCED_SYSTEM_CHECKS = [
    "admin.E410",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "user_sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    # 'django_otp.plugins.otp_email',
    "two_factor",
    # 'two_factor.plugins.phonenumber',
    # 'two_factor.plugins.yubikey',
    # 'two_factor.plugins.email',
    # 'otp_yubikey',
    "oauth2_provider",
    "phonenumber_field",  # have it, may as well use it.
    "django_login_history",  # may not want this if we log via syslog and signals
    "captcha",
    "users",
    "appdb",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "user_sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "oauth2_provider.middleware.OAuth2TokenMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# both sessions changes above, and this, are for django-user-sessions
SESSION_ENGINE = "user_sessions.backends.db"

ROOT_URLCONF = "sso.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            str(BASE_DIR.joinpath("templates")),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sso.wsgi.application"

from sso.secrets import (
    DBHOST,
    DBNAME,
    DBPASS,
    DBPORT,
    DBUSER,
    LDAP_NAME,
    LDAP_PASS,
    LDAP_USER,
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DBNAME,
        "USER": DBUSER,
        "PASSWORD": DBPASS,
        "HOST": DBHOST,
        "PORT": DBPORT,
        # 'OPTIONS': { "init_command": "SET foreign_key_checks = 0;", },
    },
    "ldap": {
        "ENGINE": "ldapdb.backends.ldap",
        "NAME": LDAP_NAME,
        "USER": LDAP_USER,
        "PASSWORD": LDAP_PASS,
    },
}
DATABASE_ROUTERS = ["ldapdb.router.Router"]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = str(BASE_DIR.joinpath("static"))

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = [
    "sso.auth.EmailBackend",
    "oauth2_provider.backends.OAuth2Backend",
]

# APPEND_SLASH = False
APPEND_SLASH = True

LOGIN_URL = "two_factor:login"
# LOGIN_URL = '/login/'
LOGOUT_URL = "/logout/"

# this one is optional
# LOGIN_REDIRECT_URL = 'two_factor:profile'
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# fix me for emails to actually go out
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = str(BASE_DIR.joinpath("sent_emails"))

# this is needed for emails to be usernames
AUTH_USER_MODEL = "users.CustomUser"

# 2FA malarkey
TWO_FACTOR_PATCH_ADMIN = True

# TWO_FACTOR_CALL_GATEWAY = 'two_factor.gateways.twilio.gateway.Twilio'
# TWO_FACTOR_CALL_GATEWAY = 'two_factor.gateways.fake.Fake'
TWO_FACTOR_CALL_GATEWAY = None

TWO_FACTOR_SMS_GATEWAY = None

TWO_FACTOR_TOTP_DIGITS = 6  # default is 6
TWO_FACTOR_LOGIN_TIMEOUT = 600  # default is 600

PHONENUMBER_DEFAULT_REGION = None

# TWO_FACTOR_REMEMBER_COOKIE_AGE = 36500  # default is 0, not active

# phonenumber stuff (using phonenumberslite)
# PHONENUMBER_DB_FORMAT = 'E164', 'INTERNATIONAL', 'NATIONAL' or 'RFC3966'
PHONENUMBER_DB_FORMAT = "E164"

# setup logging to file

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/tmp/django.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}
