# Generated by Django 3.0.14 on 2022-04-13 05:49

import ldapdb.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LdapGroup",
            fields=[
                (
                    "dn",
                    ldapdb.models.fields.CharField(
                        max_length=200, primary_key=True, serialize=False
                    ),
                ),
                (
                    "gid",
                    ldapdb.models.fields.IntegerField(
                        db_column="gidNumber", unique=True
                    ),
                ),
                (
                    "name",
                    ldapdb.models.fields.CharField(
                        db_column="cn", max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("members", ldapdb.models.fields.ListField(db_column="memberUid")),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LdapUser",
            fields=[
                (
                    "dn",
                    ldapdb.models.fields.CharField(
                        max_length=200, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    ldapdb.models.fields.CharField(
                        db_column="cn", max_length=64, unique=True
                    ),
                ),
                (
                    "username",
                    ldapdb.models.fields.CharField(
                        db_column="uid",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uid",
                    ldapdb.models.fields.IntegerField(
                        db_column="uidNumber", unique=True
                    ),
                ),
                ("gid", ldapdb.models.fields.IntegerField(db_column="gidNumber")),
                (
                    "firstname",
                    ldapdb.models.fields.CharField(
                        blank=True, db_column="givenName", default="", max_length=64
                    ),
                ),
                (
                    "lastname",
                    ldapdb.models.fields.CharField(
                        blank=True, db_column="sn", default="", max_length=64
                    ),
                ),
                (
                    "homedir",
                    ldapdb.models.fields.CharField(
                        blank=True, db_column="homeDirectory", default="", max_length=64
                    ),
                ),
                (
                    "shell",
                    ldapdb.models.fields.CharField(
                        blank=True, db_column="loginShell", default="", max_length=64
                    ),
                ),
                ("sshkeys", ldapdb.models.fields.ListField(db_column="sshPublicKey")),
                (
                    "objectclass",
                    ldapdb.models.fields.ListField(db_column="objectClass"),
                ),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
    ]
